version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "weather-demo"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-140fi4sh31qg6"
s3_prefix = "weather-demo"
region = "us-west-1"
capabilities = "CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Client=\"https://serverless-weather.com\""
